---
- name: Install Rambox
  become: yes
  dnf: 
    name: https://github.com/saenzramiro/rambox/releases/download/0.5.17/Rambox-0.5.17-x64.rpm
    state: present
  when: ansible_distribution == "Fedora"